module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: [],
  theme: {
    extend: {
      textColor: {
        primary: "#558c4c",
        secondary: "rgba(85,140,76,0.2)",
        primary_red: "#e02b20",
        primary_grey: "#666666",
      },
      borderColor: {
        primary: "#558c4c",
        secondary: "rgba(85,140,76,0.2)",
        primary_red: "#e02b20",
        primary_grey: "#666666",
      },
      backgroundColor: {
        primary: "#558c4c",
        secondary: "rgba(85,140,76,0.2)",
        primary_red: "#e02b20",
        primary_grey: "#666666",
      },
      boxShadow: {
        primary: "0px 2px 20px 10px rgb(85 140 76 / 80%)",
        secondary: "0px 3px 18px 0px rgb(0 0 0 / 40%)",
      },
      spacing: {
        "1/2": "50%",
        "1/3": "33.333333%",
        "2/3": "66.666667%",
        "1/4": "25%",
        "2/4": "50%",
        "3/4": "75%",
        "1/5": "20%",
        "2/5": "40%",
        "3/5": "60%",
        "4/5": "80%",
        "1/6": "16.666667%",
        "2/6": "33.333333%",
        "3/6": "50%",
        "4/6": "66.666667%",
        "5/6": "83.333333%",
        "1/12": "8.333333%",
        "2/12": "16.666667%",
        "3/12": "25%",
        "4/12": "33.333333%",
        "5/12": "41.666667%",
        "6/12": "50%",
        "7/12": "58.333333%",
        "8/12": "66.666667%",
        "9/12": "75%",
        "10/12": "83.333333%",
        "11/12": "91.666667%",
        full: "100%",
        screen: "100vw",
      },
      inset: (theme) => ({
        ...theme("spacing"),
      }),
    },
    screens: {
      xsm: "375px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1430px",
    },
    fontFamily: {
      roboto: ["Roboto"],
      fontAwesome: ["FontAwesome"],
    },
  },
  variants: {
    backgroundColor: [
      "responsive",
      "group-hover",
      "group-focus",
      "focus-within",
      "first",
      "last",
      "odd",
      "even",
      "hover",
      "focus",
      "active",
      "visited",
      "disabled",
    ],
    // ...
    borderColor: [
      "responsive",
      "group-hover",
      "group-focus",
      "focus-within",
      "first",
      "last",
      "odd",
      "even",
      "hover",
      "focus",
      "active",
      "visited",
      "disabled",
    ],
    // ...
    textColor: [
      "responsive",
      "group-hover",
      "group-focus",
      "focus-within",
      "first",
      "last",
      "odd",
      "even",
      "hover",
      "focus",
      "active",
      "visited",
      "disabled",
    ],
    letterSpacing: [
      "responsive",
      "group-hover",
      "group-focus",
      "focus-within",
      "first",
      "last",
      "odd",
      "even",
      "hover",
      "focus",
      "active",
      "visited",
      "disabled",
    ],
    display: [
      "responsive",
      "group-hover",
      "group-focus",
      "focus-within",
      "first",
      "last",
      "odd",
      "even",
      "hover",
      "focus",
      "active",
      "visited",
      "disabled",
    ],
    position: [
      "responsive",
      "group-hover",
      "group-focus",
      "focus-within",
      "first",
      "last",
      "odd",
      "even",
      "hover",
      "focus",
      "active",
      "visited",
      "disabled",
    ],
    margin: [
      "responsive",
      "group-hover",
      "group-focus",
      "focus-within",
      "first",
      "last",
      "odd",
      "even",
      "hover",
      "focus",
      "active",
      "visited",
      "disabled",
    ],
  },

  plugins: [],
};
